name: 'devservices setup'
description: 'Sets up devservices and validates the configuration for a given service.'
inputs:
  devservices-version:
    description: 'devservices version'
    required: true
  python-version:
    description: 'The python version to run CI with.'
    required: true
    default: 3.11

env:
  DISABLE_SENTRY: 1

runs:
  using: 'composite'
  steps:
    - uses: astral-sh/setup-uv@884ad927a57e558e7a70b92f2bccf9198a4be546 # v6
      with:
        version: '0.8.2'
        # we just cache the venv-dir directly in action-setup-venv
        enable-cache: false

    - run: echo "devservices==${{ inputs.devservices-version }}" > requirements.txt

    - uses: getsentry/action-setup-venv@3a832a9604b3e1a4202ae559248f26867b467cc7 # v2.1.1
      id: venv
      with:
        python-version: ${{ inputs.python-version }}
        cache-dependency-path: requirements.txt
        install-cmd: uv pip install -r requirements.txt

    - name: 'Run devservices in default mode'
      shell: bash
      run: devservices up

    - name: 'Run devservices status'
      shell: bash
      run: devservices status

    - name: 'Run devservices list-dependencies'
      shell: bash
      run: devservices list-dependencies

    - name: 'Run devservices logs'
      shell: bash
      run: devservices logs

    - name: 'Run devservices down'
      shell: bash
      run: devservices down
