name: 'devservices setup'
description: 'Sets up devservices and validates the configuration for a given service.'
inputs:
  requirements-file-path:
    description: 'The path to the requirements.txt file.'
    required: true
  python-version:
    description: 'The python version to run CI with.'
    required: true
    default: 3.11

env:
  DISABLE_SENTRY: 1

runs:
  using: 'composite'
  steps:
    - uses: getsentry/action-setup-venv@3a832a9604b3e1a4202ae559248f26867b467cc7 #v2.1.1
      id: venv
      with:
        python-version: ${{ inputs.python-version }}
        cache-dependency-path: ${{ inputs.requirements-file-path }}
        install-cmd: pip install -r ${{ inputs.requirements-file-path }}

    - name: 'Run devservices in default mode'
      shell: bash
      run: devservices up

    - name: 'Run devservices status'
      shell: bash
      run: devservices status

    - name: 'Run devservices list-dependencies'
      shell: bash
      run: devservices list-dependencies

    - name: 'Run devservices logs'
      shell: bash
      run: devservices logs

    - name: 'Run devservices down'
      shell: bash
      run: devservices down
