name: 'devservices setup'
description: 'Sets up devservices and validates the configuration for a given service.'

runs:
  using: 'composite'
  steps:
    - uses: getsentry/action-setup-venv@v2.1.0
      id: venv
      with:
        python-version: 3.12
        install-cmd: pip install devservices>=1.0.7 packaging

    - name: 'Run devservices in default mode'
      shell: bash
      run: devservices up

    - name: 'Run devservices status'
      shell: bash
      run: devservices status

    - name: 'Run devservices list-dependencies'
      shell: bash
      run: devservices list-dependencies

    - name: 'Run devservices logs'
      shell: bash
      run: devservices logs

    - name: 'Run devservices down'
      shell: bash
      run: devservices down
